services:
  wazuh.manager:
    image: wazuh/wazuh-manager:4.14.3
    container_name: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
      - "55000:55000/tcp"
