version: '3.8'

services:
  wazuh-indexer:
    image: wazuh/wazuh-indexer:4.14.3
    container_name: wazuh-indexer
    hostname: wazuh-indexer
    restart: unless-stopped
    ports:
      - "9200:9200"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    networks:
      - wazuh
    volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer

  wazuh.manager:
    image: wazuh/wazuh-manager:4.14.3
    container_name: wazuh-manager
    hostname: wazuh-manager
    restart: unless-stopped
    ports:
      - "1514:1514/udp"
      - "1515:1515/tcp"
      - "55000:55000/tcp"
    networks:
      - wazuh
    volumes:
      - wazuh-manager-config:/var/ossec/etc
      - wazuh-manager-logs:/var/ossec/logs

  wazuh-dashboard:
    image: wazuh/wazuh-dashboard:4.14.3
    container_name: wazuh-dashboard
    hostname: wazuh-dashboard
    restart: unless-stopped
    ports:
      - "443:5601"
    environment:
      - INDEXER_USERNAME=admin
      - INDEXER_PASSWORD=SecretPassword
      - WAZUH_API_URL=https://wazuh-manager
      - DASHBOARD_USERNAME=kibanaserver
      - DASHBOARD_PASSWORD=kibanaserver
      - API_USERNAME=wazuh-wui
      - API_PASSWORD=MyS3cr37P450r.*-
    networks:
      - wazuh
    depends_on:
      - wazuh-indexer
      - wazuh.manager

networks:
  wazuh:
    driver: bridge

volumes:
  wazuh-indexer-data:
  wazuh-manager-config:
  wazuh-manager-logs:
